version: "3"
services:
  jumia_app_exercise:
    image: hassanelseoudy97/jumia_app_exercise:latest
    ports:
      - "8080:8080"
    networks:
      - jumia-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - jumia-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=jumia
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

networks:
  jumia-mysql: