spring:
  application.name: jumia-app

  datasource:
    url: jdbc:mysql://mysqldb:3306/jumia?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: password
    initialization-mode: always
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  servlet:
    context-path: /api/v1/jumia