spring:
  datasource:
    url: jdbc:mysql://localhost/jumia?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql
    initialization-mode: always
